version: '2.1'

services:
  react_study:
    image: webpack_study
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks: 
      - react_study

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks: 
      - react_study

networks: 
  react_study: